name: CI

env:
  GRADLE_VERSION: 6.7.1

on: [push, pull_request]

jobs:
  build:
    name: Build Jenkins' jabber-plugin

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ 1.8, 11 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # Caches
      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            maven-
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-caches-${{ hashFiles('**/build.gradle') }}
          restore-keys:
            gradle-caches
      - name: Cache Gradle Binary
        uses: actions/cache@v2
        with:
          path: |
            ~/gradle-bin-${GRADLE_VERSION}/
          key: gradle-bin-${GRADLE_VERSION}

      # Pre-reqs
      - name: Grab gradle wrapper
        run: |
          wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-all.zip
          unzip gradle-${GRADLE_VERSION}-all.zip
          echo "PATH_TO_GRADLE=./gradle-${GRADLE_VERSION}/bin/gradle" >> $GITHUB_ENV

      - name: Gradle Check
        run: ${PATH_TO_GRADLE} check --stacktrace

      - name: Create JPI
        run: ${PATH_TO_GRADLE} jpi --stacktrace

      - name: Archive JPI artifact
        uses: actions/upload-artifact@v2
        with:
          name: jabber.hpi
          path: build/libs/jabber.hpi
